### ISSUE TITLE
Laravel 5.1

### ISSUE THREAD

**Issue by GregHolmes** [Vinelab/url-shortener#16]
Will there be any support for using Laravel 5.1?

  Problem 1
    - Conclusion: remove laravel/framework v5.1.10
    - Conclusion: don't install laravel/framework v5.1.10
    - vinelab/url-shortener 1.0.0 requires illuminate/support 5.0.\* -> satisfiable by illuminate/support[v5.0.0, v5.0.22, v5.0.25, v5.0.26, v5.0.28, v5.0.33, v5.0.4].
    - vinelab/url-shortener v1.1.0 requires illuminate/support 5.0.\* -> satisfiable by illuminate/support[v5.0.0, v5.0.22, v5.0.25, v5.0.26, v5.0.28, v5.0.33, v5.0.4].
    - vinelab/url-shortener v1.1.1 requires illuminate/support 5.0.\* -> satisfiable by illuminate/support[v5.0.0, v5.0.22, v5.0.25, v5.0.26, v5.0.28, v5.0.33, v5.0.4].
    - don't install illuminate/support v5.0.0|don't install laravel/framework v5.1.10
    - don't install illuminate/support v5.0.22|don't install laravel/framework v5.1.10
    - don't install illuminate/support v5.0.25|don't install laravel/framework v5.1.10
    - don't install illuminate/support v5.0.26|don't install laravel/framework v5.1.10
    - don't install illuminate/support v5.0.28|don't install laravel/framework v5.1.10
    - don't install illuminate/support v5.0.33|don't install laravel/framework v5.1.10
    - don't install illuminate/support v5.0.4|don't install laravel/framework v5.1.10
    - Installation request for laravel/framework == 5.1.10.0 -> satisfiable by laravel/framework[v5.1.10].
    - Installation request for vinelab/url-shortener \* -> satisfiable by vinelab/url-shortener[1.0.0, v1.1.0, v1.1.1].

**Comment by tusharvikky** [comment]
Any Update on this?

**Comment by will666** [comment]
Same here, so no update?

**Comment by trustylabs** [comment]
+1

**Comment by imuller** [comment]
+1

**Comment by mineass** [comment]
+1
