### ISSUE TITLE
Can not install

### ISSUE THREAD

**Issue by mskenderian** [Vinelab/url-shortener#20]
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install vinelab/url-shortener v1.2.0
    - Installation request for symfony/finder (locked at v3.0.4) -> satisfiable by symfony/finder[v3.0.4].
    - Conclusion: remove laravel/framework v5.2.30
    - Conclusion: don't install laravel/framework v5.2.30
    - vinelab/url-shortener 1.0.0 requires illuminate/support 5.0.\* -> satisfiable by illuminate/support[v5.0.0, v5.0.22, v5.0.25, v5.0.26, v5.0.28, v5.0.33, v5.0.4].
    - vinelab/url-shortener v1.1.0 requires illuminate/support 5.0.\* -> satisfiable by illuminate/support[v5.0.0, v5.0.22, v5.0.25, v5.0.26, v5.0.28, v5.0.33, v5.0.4].
    - vinelab/url-shortener v1.1.1 requires illuminate/support 5.0.\* -> satisfiable by illuminate/support[v5.0.0, v5.0.22, v5.0.25, v5.0.26, v5.0.28, v5.0.33, v5.0.4].
    - don't install illuminate/support v5.0.0|don't install laravel/framework v5.2.30
    - don't install illuminate/support v5.0.22|don't install laravel/framework v5.2.30
    - don't install illuminate/support v5.0.25|don't install laravel/framework v5.2.30
    - don't install illuminate/support v5.0.26|don't install laravel/framework v5.2.30
    - don't install illuminate/support v5.0.28|don't install laravel/framework v5.2.30
    - don't install illuminate/support v5.0.33|don't install laravel/framework v5.2.30
    - don't install illuminate/support v5.0.4|don't install laravel/framework v5.2.30
    - Installation request for laravel/framework (locked at v5.2.30, required as 5.2.*) -> satisfiable by laravel/framework[v5.2.30].
    - Installation request for vinelab/url-shortener \* -> satisfiable by vinelab/url-shortener[1.0.0, v1.1.0, v1.1.1, v1.2.0].

Installation failed, reverting ./composer.json to its original content.

**Comment by EventFellows** [comment]
Any solution yet?
I still get the same error with Laravel 5.2.43

**Comment by EventFellows** [comment]
I have now removed 'illuminate/html' and for some reason now it works

**Comment by adrianhaurat** [comment]
Had the same issue when running `composer require vinelab/url-shortener:*`

As a workaround, I was able to install by manually adding `"vinelab/url-shortener": "*"` to my composer.json and running `composer update`.

**Comment by stueynet** [comment]
Same issue. @adrianhaurat not solving it for me. Very odd.

**Comment by alberto-bottarini** [comment]
:-1: 

Same problem for me
